# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" your repository name
url: "https://ibrahimdevx.github.io"
baseurl: "/E"
siteIcon: 
siteYear: 2021
siteFooterlink: /404
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: Inferno network
serverDescription: idk what to write here lol
serverIP: 51.178.221.3:25642
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/qCwW6efbQT
discordServerID: 860126624497139772
discordChannelID: 881960287572488284


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Server Map
#     url: map
#     newtab: true
#   - name: Screenshots
#     url: screenshots
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
